Dig 23809 build fis bones
npr/feed-ingest-service pull request #1
Opened 2020-09-16 20:27 UTC by marcjones-io

Goals of this ticket:
- Init the repo + README
- Update WebSub proto to TS
- Lay pipes through which unknown substances will flow (vague, yes I'm aware.)

My attempt at kicking this off pulled me in a number of directions and this PR is a representation of trying to reconcile those different paths. There is still work to be done on the websub side of things, specifically: integrating with parse + ingest processes that have yet to be developed, solving the case of the errant hub rel attribute, securing websub comms chain with a shared hub secret, unit tests, and fixing the UID hash once the CI/CD pipeline is put in place -- all of which are commented in code.

After today's meeting and the realigned priority order, I didn't want to get bogged down in work that had yet to be properly scoped and thought it best to leave this in the current state as a jump off for the rest of the FIS to be developed.

Looking for thoughts, productive critique, and suggestions for improvement.

2020-09-17 14:56 UTC, marcjones-io commented on src/index.ts
> +router
try/catch blocks needed for each route for proper error handling

2020-09-17 14:59 UTC, marcjones-io commented on src/websub/controller.ts
> +async function makeSubscriptionRequest(ctx: Context): Promise<number> {
feel like the return signature here shouldn't be coupled to the status code, and that there is a better way to bubble up errors/successes without having them tied here

2020-09-17 15:02 UTC, marcjones-io commented on src/index.ts
> +    // console.log(`CTX: ${JSON.stringify(ctx)}`);
should be at least logging these requests being made by a hub so we can see the incoming data that will inevitably be passed into our tbd ingest process

2020-09-17 20:46 UTC, bwestergard requested changes
Looks good. Requesting some small changes.

2020-09-17 20:46 UTC, bwestergard commented on README.md
> +The Feed Ingest Service (FIS) functions to incorporate podcasts managed by internal users at NPR, member stations, and 3rd parties into the Content Service. It offers a user interface with varying de
Good summary.

2020-09-17 20:46 UTC, bwestergard commented on package.json
> +    "lodash": "^4.17.20",
There is nothing you can do in lodash more easily than in vanilla javascript, change my mind. :-)

2020-09-17 20:46 UTC, bwestergard commented on src/index.ts
> +    // console.log(`CTX: ${JSON.stringify(ctx)}`);
Probably good to remove these comments before merging. You can always hang on to them in branch.

2020-09-17 20:46 UTC, bwestergard commented on src/websub/controller.ts
> +  const feedUrl = _.get(ctx, 'request.body[feed]');
Can't you just do this with `ctx.request.body['feed']` or `ctex.request.body.feed`? If we are dependent on the type of the body (it appears we are), we need to add checks here anyway, so `lodash`'s "smile through the pain" semantics don't really help us.

2020-09-17 20:46 UTC, bwestergard commented on src/websub/controller.ts
> +    // 'hub.secret': '123456789',
This all seems legit. We're punting on the shared secret authentication for now, right? Do we have a ticket for that?

2020-09-17 20:46 UTC, bwestergard commented on src/websub/controller.ts
> +  if (status !== 202) {
Is this the only code we'll accept? Seems fine if so, just checking because I'm not familiar with the spec.

2020-09-17 20:46 UTC, bwestergard commented on src/websub/util.ts
> +  const feedTitle = _.get(feed, 'rss.channel[0].title[0]');
See above comments about `lodash`.

2020-09-17 20:46 UTC, bwestergard commented on tslint.json
> +{
This all looks good. Can we add strict null/undefined checking?

2020-09-21 17:43 UTC, universalhandle requested changes

2020-09-21 17:43 UTC, universalhandle commented on src/websub/util.ts
> +function findHubUrl(feed: object): string | null {
Can we type more strongly than `object`?

2020-09-21 17:43 UTC, universalhandle commented on src/websub/util.ts
> +  if (links.length < 2) {
If something about the first link is disqualifying/assumed, it should be noted in a comment.

2020-09-21 17:43 UTC, universalhandle commented on src/websub/util.ts
> +  return (webSubHubURL);
Why the parens?

2020-09-21 17:43 UTC, universalhandle commented on src/websub/util.ts
> + * - findHubUrl() needs re-worked to find all possible spots for rel="hub" - perhaps a simple string search?
I would advise against a string search.

Reference: The AdsWizz saga of 2020.

2020-09-21 17:43 UTC, universalhandle commented on tsconfig.json
> +    "strictNullChecks": true,
Yes, thank you!

2020-09-21 17:43 UTC, universalhandle commented on tslint.json
> +{
Does that do something different from `strictNullChecks` in tsconfig.json?

2020-09-21 17:43 UTC, universalhandle commented on tslint.json
> +}
I didn't look at these too hard, but [ATM's](https://github.com/npr/audio-tag-manager/blob/main/backend/tslint.json) is much longer (so I suspect more opinionated). I think there's value in having consistent standards across projects, making exceptions only where needed/appropriate.

2020-09-21 17:43 UTC, universalhandle commented on package.json
> +  "scripts": {
I think the documentation and/or npm scripts need to better inform a newcoming developer such as myself how to build/start/deploy the app.

Relatedly, I am fairly new to lambda but I think some of the lessons I've learned around Docker and environment management apply here. Elsewhere you've identified problems running the code that you built in your Mac environment on the Linux-based AWS environment. A quick search turned up [this set of Docker images](https://hub.docker.com/r/lambci/lambda/) which would allow you to build (and locally run) the project in a close approximation of the runtime environment. It's even [mentioned](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-layer-simulated-docker/) in the official docs.

I don't know whether this is the subject of your current ticket or another one, but I'd say it's a pretty high priority to stabilize the development environment sooner than later.

2020-09-22 16:46 UTC, marcjones-io commented on src/websub/controller.ts
> +    // 'hub.secret': '123456789',
No ticket yet - can create one - this work will be part of the WebSub epic

2020-09-22 17:15 UTC, marcjones-io commented on src/websub/controller.ts
> +  if (status !== 202) {
Yes it is the[ only acceptable response](https://www.w3.org/TR/websub/#x5-1-2-subscription-response-details)

2020-09-22 17:21 UTC, marcjones-io commented on serverless.yml
> +  runtime: nodejs12.x
[AWS Lambda runtime supports up to 12.x](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

2020-09-22 17:28 UTC, marcjones-io commented on src/websub/controller.ts
> + * - Attempt to maintain shared secret with hub
From the [W3 WebSub spec]( https://www.w3.org/TR/websub/#subscribers): "MAY include a secret in the subscription request, and if it does, then MUST use the secret to verify the signature in the content distribution request."

2020-09-22 17:40 UTC, marcjones-io commented on src/websub/util.ts
> + * - findHubUrl() needs re-worked to find all possible spots for rel="hub" - perhaps a simple string search?
Agreed. I figured this out earlier this AM using lodash's filter and find methods. The string search was simply used to confirm efficacy (96.5% all hub links successfully caught)

2020-09-22 18:30 UTC, marcjones-io commented on package.json
> +  "scripts": {
Agreed that this is a matter of importance. Our early talks with DevOps landed us with Serverless, and want to make sure we turn over every stone before giving up on what should be a relatively plug-n-play approach. FWIW I'm willing to bet that the FarmHash binary didn't translate to the AWS environment due to error on my part so I'll do some more investigating there (also worth noting there are likely a bounty of other hashing libraries that'll work fine and I could use Node's native Crypto module instead). As far as using Docker I will leave that up to you, @jsgrosman @sconnor-npr and @bwestergard for further discussion.

2020-09-22 18:33 UTC, marcjones-io commented on package.json
> +  "scripts": {
As for the start script, I'll wire it up to an local deploy for offline use of the function

2020-09-22 18:39 UTC, marcjones-io commented on src/index.ts
> +app.listen(3000);
Good catch - they'll only matter for local use but we can incorporate this as an configurable env var

2020-09-23 17:53 UTC, jsgrosman commented on .jestconfig.json
> +        "text"
Let's add HTML here, as well.

2020-09-23 17:53 UTC, jsgrosman commented on package.json
> +    "jest-nyan-reporter": "^1.0.2",
I want to ask if this is necessary, but I'll allow it. :)

2020-09-23 17:53 UTC, jsgrosman commented on tsconfig.jest.json
> +        "removeComments": false
What's the rational here? Any reason to keep comments during the unit test compile?

2020-09-24 16:22 UTC, universalhandle commented on package.json
> +    "jest-nyan-reporter": "^1.0.2",
https://www.youtube.com/watch?v=QH2-TGUlwu4&t=36s

2020-09-29 17:23 UTC, marcjones-io commented on tsconfig.jest.json
> +        "removeComments": false
This config was copy pasta from a voice repo. Nara talked me through it:

We keep the comments for Jest, overriding the [ts config](https://github.com/npr/feed-ingest-service/blob/DIG-23809-build-FIS-bones/tsconfig.json#L18) where we remove them. This way the source map from TS > JS aren't out of sync.

2020-09-29 17:32 UTC, jsgrosman commented on tsconfig.jest.json
> +        "removeComments": false
👍

2020-10-06 15:44 UTC, bwestergard approved these changes

2020-10-07 16:59 UTC, universalhandle approved these changes
Looks really good. Crisp and readable.

2020-10-07 16:59 UTC, universalhandle commented on README.md
> +Current endpoints:
Not at all a blocker to merging, and maybe my opinion alone rather than a collectively held one, but I think a Postman collection is a better way to document endpoints. (You can link to the web docs from the the README.)

What I prefer about that format:
- You can add any number of example requests
- You can add any number of example responses
- It encourage documentation of headers and parameters
- You can fire up Postman and interact with the endpoints you or your teammate has just documented

2020-10-07 16:59 UTC, universalhandle commented on src/websub/util.test.ts
> +            const result = `fis-${murmurhash.v3(hashInput).toString(36)}`;
Also not a showstopper, but I might not rely on `murmurhash` in my test and instead mock it or spy on it.

2020-10-07 16:59 UTC, universalhandle commented on src/websub/util.ts
> +function extractHubUrlFromRssFeed(xmlAst: JSONValue): Result<string, string> {
What is an `xmlAst`?

2020-10-07 16:59 UTC, universalhandle commented on src/websub/util.ts
> +            && !Array.isArray(xmlAst.rss.channel[0])
I don't know if you'll need to reuse this logic, but encapsulating it in a function would at least promote readability, e.g.:

```
if (xmAstHasChannelElement(xmlAst)) {
    // ... your logic here
}
```

... or...

```
const channelElement = extractChannelElement(xmlAst); // returns JSONObject | undefined
if (channelElement) {
    // ... your logic here...
}
```

2020-10-07 16:59 UTC, universalhandle commented on src/websub/util.ts
> +            && !Array.isArray(xmlAst.rss.channel[0])
Actually, it does look like there's similar logic in other places in this util, so, yay, dry++ and readability++!

2020-10-07 17:58 UTC, marcjones-io commented on src/websub/util.ts
> +function extractHubUrlFromRssFeed(xmlAst: JSONValue): Result<string, string> {
XML abstract syntax tree :)

2020-10-07 17:58 UTC, marcjones-io commented on src/websub/util.ts
> +function extractHubUrlFromRssFeed(xmlAst: JSONValue): Result<string, string> {
(what is returned from xml2js)

2020-10-07 18:01 UTC, marcjones-io commented on README.md
> +Current endpoints:
Agreed, I wanted something to throw in there for _us_ so people can recognize what they're working with if they try to deploy. This document will be wildly different by the time the project finishes, I do however think it's important for it to reflect it's current status

2020-10-07 18:05 UTC, marcjones-io commented on src/websub/util.ts
> +            && !Array.isArray(xmlAst.rss.channel[0])
Definitely. I envision that once our parser is written we'll have this logic encapsulated with it - and instead of parsing individual elements we can instead pass around our own JSON representation of an rss feed

2020-10-07 18:33 UTC, universalhandle commented on src/websub/util.ts
> +function extractHubUrlFromRssFeed(xmlAst: JSONValue): Result<string, string> {
Thanks. In general I recommend avoiding acronyms in variable names unless they are common knowledge, like XML. I might have called this `xmlTree` instead (but I admittedly have limited context).

2020-10-08 17:41 UTC, marcjones-io commented
Dig 23809 build fis bones:
- Init the repo + README
- Update WebSub proto to TS

2020-10-08 17:42 UTC, merged